---
- name: Launch database container
  community.docker.docker_container:
    name: database
    image: josuuk/tp-devops-database:latest
    networks:
      - name: app-network
    env:
      POSTGRES_PASSWORD: "{{ database_password }}"
    volumes:
      - db-volume:/var/lib/postgresql/data
    pull: true
    restart_policy: unless-stopped
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python